
#   FROM postgres:12-buster

#   RUN apt update && apt upgrade && \
#    apt install node

#   RUN npm insta

#   docker run --name testdb -p 9000:5432 -e POSTGRES_PASSWORD=admin -d postgres:12-buster

#   npx prisma migrate dev